apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/helm/release.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - name: promote-changelog
          resources: {}
        - image: gcr.io/jenkinsxio/helm-release:0.0.1
          name: release-chart
          resources: {}
          script: |
            #!/usr/bin/env sh
            if [ -d "/workspace/source/charts/$REPO_NAME" ]; then source .jx/variables.sh
            cd /workspace/source/charts/$REPO_NAME
            make release; else echo no charts; fi
          podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
